### ISSUE TITLE
predictable filename in /tmp

### ISSUE THREAD

**Issue by cgwalters** [rtnpro/fedora-motd#3]
```
rpm-ostree upgrade --check --preview > /tmp/rpmostree_updateinfo.out
```

is a bad idea: https://www.owasp.org/index.php/Insecure_Temporary_File

**Comment by rtnpro** [comment]
Would it be OK if I use `/var/run/rpmostree_updateinfo.out` instead of `/tmp/rpmostree_updateinfo.out`?
