### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by dustymabe** [rtnpro/fedora-motd#5]
python3 support is something we need out of the box with fedora-motd since the cloud-base image by default does not have python2 in it any longer. The python2 packages were removed from the cloud base image in F23 and it would be a step backwards to now require them in F24. 

Here is everything that gets installed when installing fedora-motd:

```
# dnf install fedora-motd --enablerepo=updates-testing 
Last metadata expiration check: 0:16:45 ago on Sun May  1 18:02:47 2016.
Dependencies resolved.
================================================================================
 Package                Arch       Version            Repository           Size
================================================================================
Installing:
 fedora-motd            noarch     0.1.2-1.fc24       updates-testing      19 k
 python                 x86_64     2.7.11-4.fc24      fedora               95 k
 python-libs            x86_64     2.7.11-4.fc24      fedora              5.8 M
 python-pip             noarch     8.0.2-1.fc24       fedora              1.7 M
 python2-setuptools     noarch     20.1.1-1.fc24      fedora              417 k
```

Ideally we would not add any packages other than `fedora-motd`.

**Comment by rtnpro** [comment]
Good point. I think it should not be a big deal, but I will cross check and
get back to you tomorrow.

**Comment by dustymabe** [comment]
Thanks! ideally it would be good if we wrote this in such a way that it was python2 or python3 compatible. That way if we ever wanted to support CentOS 7 the only change we would make is how we built the package, not the upstream code.

**Comment by dustymabe** [comment]
Cool. We'll also need to modify how the package is built and its dependencies to make sure it uses python3 vs python2 in fedora.

**Comment by rtnpro** [comment]
Yeah!

On Tue, May 3, 2016 at 11:22 AM, Dusty Mabe notifications@github.com
wrote:

> Cool. We'll also need to modify how the package is built and its
> dependencies to make sure it uses python3 vs python2 in fedora.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> https://github.com/rtnpro/fedora-motd/issues/5#issuecomment-216444224

## 

Ratnadeep Debnath,
https://www.waartaa.com
GPG Fingerprint: 033C 8041 A0E9 CDBA 2E02  B785 2119 5486 F245 DFD6

**Comment by encukou** [comment]
The [RPM porting guide](http://python-rpm-porting.readthedocs.io/en/latest/index.html) explains how to do the RPM part.

**Comment by irushchyshyn** [comment]
Hi @rtnpro, do you plan to release the version with Python 3 support (0.1.3)?

**Comment by rtnpro** [comment]
@irushchyshyn We do not yet plan to do it! But, it'll be good to have Python 3 support as well. Any contribution is super welcome.
