### ISSUE TITLE
motdgen does not write output to file in /var/run/motd

### ISSUE THREAD

**Issue by dustymabe** [rtnpro/fedora-motd#7]
With commit 62976c3 the motdgen script now longer actually captures the output of the executed commands so that it can then write that output to the file provided with `-o`. This is causing nothing to ever get written to `/var/run/motd` when it gets invoked in `pam.d/motdgen` which means nothing ever gets printed as the motd when the user logs in.

**Comment by rtnpro** [comment]
Fixed by a3b5896551f60949752ef217635dc543bbad4e33
